promtail:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus-operator
  pipelineStages:
  - match:
      selector: '{app=~"polkadot-node"}'
      stages:
      - regex:
          expression: ".*(?P<scheduled_epoch>Next epoch starts at slot)"
      - metrics:
          polkadot_epoch_scheduled_total:
            type: Counter
            description: "total count of scheduled epochs"
            source: scheduled_epoch
            config:
              action: inc
  - match:
      selector: '{app=~"polkadot-node"}'
      stages:
      - regex:
          expression: ".*(?P<started_epoch>New epoch .* launching at block)"
      - metrics:
          polkadot_epoch_started_total:
            type: Counter
            description: "total count of started epochs"
            source: started_epoch
            config:
              action: inc
