service:
  port: 31000
  targetPort: 31000
prometheus:
  monitor:
    enabled: true
    additionalLabels:
      release: prometheus-operator
resources:
  limits:
    cpu: 200m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 30Mi
